[package]
name = "false_vacuum_decay"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
once_cell = "1.19.0"
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
